### ISSUE TITLE
I Broke the Button

### ISSUE THREAD

**Issue by vizzie** [CircuitHappy/missinglink#37]
https://github.com/CircuitHappy/missinglink/blob/0b11cc5bf94802c6ca23ada35728f1f0afdcffc9/src/missing_link/control.cpp#L37

@ndonald2 I think this is the only function you should have to fix up... I hope. I don't quite understand how the button logic works, I tried to make it work, but no dice. I think the rest of the flow from User_Interface to Engine should be good to go once you are able to get the Button object working correctly.

The gestures I'm going to do are "hold encoder button, then press Tap or PlayStop button". Right now I only have one special command, to queue a StartTransport at the next Loop start. I'm sure we can come up with something to put in the other gesture... or maybe we just have it do something cheeky like tell a knock knock joke.

**Comment by ndonald2** [comment]
> The gestures I'm going to do are "hold encoder button, then press Tap or PlayStop button". 

Based on our discussion yesterday, if we go with holding the encoder as the "shift" modifier, we'll probably need to change the menu selection action to be when the encoder is _released_ - it would be annoying to have the menu change as part of the other gestures. That also means we'll need to "cancel" the encoder-up gesture if we detect one of the other ones so the menu doesn't change afterwards either.

**Comment by vizzie** [comment]
Well, it will just display the current menu label, not change menus, and then go away after a second. Shouldn’t be too much of an issue to keep encoderDown as the menu change trigger too

**Comment by ndonald2** [comment]
Gotcha 👍 sounds good to me

**Comment by ndonald2** [comment]
@vizzie Should be good to go on the `button-gestures` branch! I can hold the encoder and press tap tempo to see your "reset at loop" message scroll by. I also shook out the pesky debounce stuff so hopefully the encoder button and rotation will recognize a bit more stably/consistently now. Turned out to be related to the way the interrupt on the input expander works which is _not_ compatible with traditional single-pin debouncing techniques. Let me know if you see any issues.

**Comment by vizzie** [comment]
Thank you!! Thanks for fixing the branch. Me & Git, we don't always see
eye-to-eye on things ;-)

I'm looking forward to trying out the new branch and merging it in to the
rtmidi-package branch.

**Comment by vizzie** [comment]
looking good! I added a placeholder function for onEncoderAndPlay. I'm thinking I might set that to re-zero the timeline, so if you need to set the grid to start "now" at the start of a song.
